export type Profile = {
  id: string;
  handle: string;
  name: string;
  bio: string;
  avatar: string | null;
  link?: string | null;
  demo: number;
  created: number;
  following?: number;
  followers?: number;
  following_count?: number;
  posts_count?: number;
  official?: number;
  isAdmin?: boolean;
  nameLockedUntil?: number | null;
  onboarded?: boolean;
};
export type Post = {
  id: string;
  user_id: string;
  body: string;
  image: string | null;
  created: number;
  pinned: number;
  edited_at: number | null;
  handle: string;
  name: string;
  avatar: string | null;
  demo: number;
  official: number;
  likes: number;
  comments: number;
  liked: number;
  saved: number;
};
export type FeedCursor = { created: number; id: string };
export type FeedResponse = {
  posts: Post[];
  hasMore: boolean;
  next: FeedCursor | null;
};
export type Comment = {
  id: string;
  post_id: string;
  user_id: string;
  body: string;
  created: number;
  handle: string;
  name: string;
  avatar: string | null;
};
export type ReportGroup = {
  post_id: string;
  body: string;
  image: string | null;
  handle: string;
  count: number;
  latest: number;
  reasons: string;
};
export type FlaggedPhoto = {
  id: string;
  url: string;
  created: number;
  target: string;
  reason: string | null;
  handle: string;
  in_use: number;
};
